radix define ClassTableIndices {
	0 "java/lang/Object" -color {Green}, //n
	1 "java/util/HashMap$3" -color {Green}, //n
	2 "java/lang/Integer" -color {Green}, //n
	3 "java/util/HashMap$2" -color {Green}, //n
	4 "java/lang/IllegalMonitorStateException" -color {Green}, //n
	5 "java/util/Vector" -color {Green}, //n
	6 "java/util/AbstractMap$2" -color {Green}, //n
	7 "java/util/Collections$ReverseComparator" -color {Green}, //n
	8 "java/util/HashMap$1" -color {Green}, //n
	9 "java/util/Collections$UnmodifiableListIterator" -color {Green}, //n
	10 "gnu/regexp/RETokenEnd" -color {Green}, //n
	11 "java/io/OutputStreamWriter" -color {Green}, //n
	12 "java/util/AbstractList$SubList" -color {Green}, //n
	13 "java/util/AbstractMap$1" -color {Green}, //n
	14 "java/util/AbstractList$RandomAccessSubList" -color {Green}, //n
	15 "java/util/Arrays$ArrayList" -color {Green}, //n
	16 "java/io/PrintStream" -color {Green}, //n
	17 "gnu/regexp/CharIndexedInputStream" -color {Green}, //n
	18 "gnu/regexp/RETokenPOSIX" -color {Green}, //n
	19 "java/util/Arrays" -color {Green}, //n
	20 "java/util/AbstractList$1" -color {Green}, //n
	21 "java/util/Collections$SynchronizedMap$1" -color {Green}, //n
	22 "java/util/Collections$SingletonMap" -color {Green}, //n
	23 "java/io/FilterOutputStream" -color {Green}, //n
	24 "java/io/NullPrintStream" -color {Green}, //n
	25 "java/util/AbstractList$2" -color {Green}, //n
	26 "java/util/Collections$SingletonSet" -color {Green}, //n
	27 "gnu/regexp/CharIndexedStringBuffer" -color {Green}, //n
	28 "java/io/ObjectInputStream" -color {Green}, //n
	29 "java/io/File" -color {Green}, //n
	30 "java/lang/Thread" -color {Green}, //n
	31 "java/lang/InternalError" -color {Green}, //n
	32 "gnu/regexp/CharIndexedCharArray" -color {Green}, //n
	33 "cgra/pe/PETrigonometry" -color {Green}, //n
	34 "java/lang/StrictMath" -color {Green}, //n
	35 "java/util/Collections$SingletonMap$1" -color {Green}, //n
	36 "de/amidar/HashMapInt" -color {Green}, //n
	37 "gnu/regexp/REException" -color {Green}, //n
	38 "java/io/BufferedInputStream" -color {Green}, //n
	39 "java/util/NoSuchElementException" -color {Green}, //n
	40 "java/lang/ArrayIndexOutOfBoundsException" -color {Green}, //n
	41 "gnu/regexp/RETokenAny" -color {Green}, //n
	42 "java/lang/IllegalStateException" -color {Green}, //n
	43 "java/util/Collections$1" -color {Green}, //n
	44 "java/util/Collections$SynchronizedMap$1SynchronizedMapEntry" -color {Green}, //n
	45 "java/lang/Double" -color {Green}, //n
	46 "java/util/Collections$SynchronizedMap$1$1" -color {Green}, //n
	47 "java/lang/System" -color {Green}, //n
	48 "java/util/AbstractMap" -color {Green}, //n
	49 "de/amidar/HashMapIdentity" -color {Green}, //n
	50 "de/amidar/BitOperations" -color {Green}, //n
	51 "java/lang/UnsupportedOperationException" -color {Green}, //n
	52 "gnu/regexp/CharUnit" -color {Green}, //n
	53 "java/lang/Boolean" -color {Green}, //n
	54 "java/util/regex/Matcher" -color {Green}, //n
	55 "java/util/Collections$SingletonList" -color {Green}, //n
	56 "gnu/regexp/RETokenRepeated" -color {Green}, //n
	57 "gnu/regexp/RETokenBackRef" -color {Green}, //n
	58 "java/lang/StackOverflowError" -color {Green}, //n
	59 "java/util/Collections$EmptySet" -color {Green}, //n
	60 "java/util/HashMap$HashEntry" -color {Green}, //n
	61 "de/amidar/HashMapInt$HashEntryInt" -color {Green}, //n
	62 "gnu/regexp/REMatchEnumeration" -color {Green}, //n
	63 "gnu/regexp/RETokenEndSub" -color {Green}, //n
	64 "java/lang/NullPointerException" -color {Green}, //n
	65 "java/io/IOException" -color {Green}, //n
	66 "gps/test/AcuisitionTest" -color {Green}, //n
	67 "gnu/regexp/IntPair" -color {Green}, //n
	68 "java/lang/StringIndexOutOfBoundsException" -color {Green}, //n
	69 "java/util/Collections$UnmodifiableMap$UnmodifiableEntrySet$1" -color {Green}, //n
	70 "java/util/Collections$SynchronizedCollection" -color {Green}, //n
	71 "java/lang/Number" -color {Green}, //n
	72 "java/lang/VirtualMachineError" -color {Green}, //n
	73 "de/amidar/scheduler/Monitor" -color {Green}, //n
	74 "gnu/regexp/REMatch" -color {Green}, //n
	75 "java/lang/IndexOutOfBoundsException" -color {Green}, //n
	76 "java/lang/IllegalArgumentException" -color {Green}, //n
	77 "java/util/Collections$CopiesList" -color {Green}, //n
	78 "java/util/Collections$UnmodifiableList" -color {Green}, //n
	79 "java/lang/Long" -color {Green}, //n
	80 "java/lang/Character$UnicodeBlock" -color {Green}, //n
	81 "java/io/OutputStream" -color {Green}, //n
	82 "java/lang/IncompatibleClassChangeError" -color {Green}, //n
	83 "java/util/Collections$SynchronizedIterator" -color {Green}, //n
	84 "java/lang/NegativeArraySizeException" -color {Green}, //n
	85 "java/util/AbstractList" -color {Green}, //n
	86 "java/lang/StackTraceElement" -color {Green}, //n
	87 "java/util/Random" -color {Green}, //n
	88 "java/lang/Error" -color {Green}, //n
	89 "java/util/ConcurrentModificationException" -color {Green}, //n
	90 "gnu/regexp/RETokenWordBoundary" -color {Green}, //n
	91 "java/io/Writer" -color {Green}, //n
	92 "java/io/ObjectOutputStream" -color {Green}, //n
	93 "java/util/ArrayList" -color {Green}, //n
	94 "gnu/regexp/RETokenRange" -color {Green}, //n
	95 "de/amidar/HashMapIdentity$HashEntryIdentity" -color {Green}, //n
	96 "gnu/regexp/REToken" -color {Green}, //n
	97 "java/util/Collections$UnmodifiableMap$UnmodifiableEntrySet" -color {Green}, //n
	98 "java/util/regex/Pattern" -color {Green}, //n
	99 "java/util/Collections$UnmodifiableMap$UnmodifiableEntrySet$1$1" -color {Green}, //n
	100 "java/lang/Throwable" -color {Green}, //n
	101 "java/util/AbstractMap$BasicMapEntry" -color {Green}, //n
	102 "java/io/UnsupportedEncodingException" -color {Green}, //n
	103 "java/util/AbstractCollection" -color {Green}, //n
	104 "java/util/AbstractMap$1$1" -color {Green}, //n
	105 "java/util/Collections$UnmodifiableCollection" -color {Green}, //n
	106 "java/util/Locale" -color {Green}, //n
	107 "java/lang/Exception" -color {Green}, //n
	108 "de/amidar/scheduler/Scheduler" -color {Green}, //n
	109 "java/util/HashMap$HashIterator" -color {Green}, //n
	110 "gnu/regexp/RESyntax" -color {Green}, //n
	111 "java/util/regex/PatternSyntaxException" -color {Green}, //n
	112 "gps/acquisition/Acquisition" -color {Green}, //n
	113 "gnu/regexp/RETokenStart" -color {Green}, //n
	114 "java/lang/String$CaseInsensitiveComparator" -color {Green}, //n
	115 "gnu/regexp/RE" -color {Green}, //n
	116 "de/amidar/scheduler/SchedulerThread" -color {Green}, //n
	117 "java/lang/NumberFormatException" -color {Green}, //n
	118 "java/util/BitSet" -color {Green}, //n
	119 "java/util/Collections$EmptyMap" -color {Green}, //n
	120 "java/util/Collections" -color {Green}, //n
	121 "java/util/Collections$SynchronizedMap" -color {Green}, //n
	122 "java/lang/RuntimeException" -color {Green}, //n
	123 "java/util/Collections$SynchronizedSet" -color {Green}, //n
	124 "java/util/Collections$SynchronizedSortedMap" -color {Green}, //n
	125 "java/lang/IllegalAccessError" -color {Green}, //n
	126 "java/util/Collections$EmptyList" -color {Green}, //n
	127 "java/util/AbstractSet" -color {Green}, //n
	128 "java/util/HashMap" -color {Green}, //n
	129 "java/util/Collections$UnmodifiableSortedSet" -color {Green}, //n
	130 "java/lang/InterruptedException" -color {Green}, //n
	131 "java/lang/reflect/Array" -color {Green}, //n
	132 "java/io/FileInputStream" -color {Green}, //n
	133 "de/amidar/HashMapInt$HashIterator" -color {Green}, //n
	134 "java/lang/Float" -color {Green}, //n
	135 "java/util/Collections$SynchronizedRandomAccessList" -color {Green}, //n
	136 "java/util/Collections$UnmodifiableSortedMap" -color {Green}, //n
	137 "java/lang/StringBuffer" -color {Green}, //n
	138 "gnu/regexp/RETokenOneOf" -color {Green}, //n
	139 "de/amidar/HashMapIdentity$HashIterator" -color {Green}, //n
	140 "java/lang/Short" -color {Green}, //n
	141 "java/io/InputStream" -color {Green}, //n
	142 "java/util/Collections$SynchronizedListIterator" -color {Green}, //n
	143 "java/lang/String" -color {Green}, //n
	144 "java/lang/Character" -color {Green}, //n
	145 "de/amidar/AmidarSystem" -color {Green}, //n
	146 "java/io/PrintWriter" -color {Green}, //n
	147 "java/lang/ClassNotFoundException" -color {Green}, //n
	148 "java/util/Collections$UnmodifiableMap" -color {Green}, //n
	149 "java/io/FilterInputStream" -color {Green}, //n
	150 "java/util/AbstractList$SubList$1" -color {Green}, //n
	151 "java/util/Collections$UnmodifiableSet" -color {Green}, //n
	152 "java/util/AbstractMap$2$1" -color {Green}, //n
	153 "java/lang/Math" -color {Green}, //n
	154 "java/lang/Byte" -color {Green}, //n
	155 "java/util/Vector$1" -color {Green}, //n
	156 "java/util/Collections$UnmodifiableIterator" -color {Green}, //n
	157 "gnu/regexp/CharIndexedString" -color {Green}, //n
	158 "java/util/Collections$SingletonSet$1" -color {Green}, //n
	159 "java/lang/CloneNotSupportedException" -color {Green}, //n
	160 "java/util/Collections$UnmodifiableRandomAccessList" -color {Green}, //n
	161 "java/lang/LinkageError" -color {Green}, //n
	162 "gnu/regexp/RETokenChar" -color {Green}, //n
	163 "java/lang/Character$Subset" -color {Green}, //n
	164 "java/lang/Class" -color {Green}, //n
	165 "java/util/Collections$SynchronizedSortedSet" -color {Green}, //n
	166 "de/amidar/FrameStack" -color {Green}, //n
	167 "java/util/Collections$SynchronizedList" -color {Green}, //n
	168 "java/lang/Comparable" -color {Blue}, //n 
	169 "gnu/regexp/CharIndexed" -color {Blue}, //n 
	170 "java/lang/Runnable" -color {Blue}, //n 
	171 "java/util/Iterator" -color {Blue}, //n 
	172 "java/lang/Cloneable" -color {Blue}, //n 
	173 "java/util/Map" -color {Blue}, //n 
	174 "java/io/Serializable" -color {Blue}, //n 
	175 "java/util/Enumeration" -color {Blue}, //n 
	176 "java/util/SortedSet" -color {Blue}, //n 
	177 "de/amidar/AmidarPeripheral" -color {Blue}, //n 
	178 "java/util/Collection" -color {Blue}, //n 
	179 "gnu/java/lang/CharData" -color {Blue}, //n 
	180 "java/util/SortedMap" -color {Blue}, //n 
	181 "java/util/List" -color {Blue}, //n 
	182 "java/util/RandomAccess" -color {Blue}, //n 
	183 "java/util/Set" -color {Blue}, //n 
	184 "java/util/Comparator" -color {Blue}, //n 
	185 "java/util/Map$Entry" -color {Blue}, //n 
	186 "java/lang/CharSequence" -color {Blue}, //n 
	187 "java/util/ListIterator" -color {Blue}, //n 
	188 "[Z" -color {Yellow}, //n 
	189 "[C" -color {Yellow}, //n 
	190 "[F" -color {Yellow}, //n 
	191 "[[F" -color {Yellow}, //n 
	192 "[D" -color {Yellow}, //n 
	193 "[B" -color {Yellow}, //n 
	194 "[S" -color {Yellow}, //n 
	195 "[I" -color {Yellow}, //n 
	196 "[J" -color {Yellow}, //n 
	197 "[Ljava/lang/Integer" -color {Yellow}, //n 
	198 "[Lgnu/regexp/REMatch" -color {Yellow}, //n 
	199 "[Lde/amidar/HashMapIdentity$HashEntryIdentity" -color {Yellow}, //n 
	200 "[Ljava/util/HashMap$HashEntry" -color {Yellow}, //n 
	201 "[Ljava/lang/Object" -color {Yellow}, //n 
	202 "[Ljava/lang/String" -color {Yellow}, //n 
	203 "[Ljava/lang/Character$UnicodeBlock" -color {Yellow}, //n 
	204 "[Lde/amidar/HashMapInt$HashEntryInt" -color {Yellow}, //n 
	205 "[Ljava/lang/StackTraceElement" -color {Yellow}, //n 
	206 "[Ljava/lang/Class" -color {Yellow}, //n 
	-default unsigned
	-defaultcolor {Red}
}
